-- Los drops funcionan en la versión 23ai en adelante
--DROP TABLE IF EXISTS tk_usuarios CASCADE CONSTRAINTS purge;
--DROP TABLE IF EXISTS tk_roles CASCADE CONSTRAINTS purge;
--DROP TABLE IF EXISTS tk_usuarios_roles CASCADE CONSTRAINTS purge;
--DROP TABLE IF EXISTS tk_comentarios CASCADE CONSTRAINTS purge;
--DROP TABLE IF EXISTS TK_AREAS CASCADE CONSTRAINTS purge;
--DROP TABLE IF EXISTS Tk_CATEGORIAS CASCADE CONSTRAINTS purge;
--DROP TABLE IF EXISTS TK_TICKET_ADJUNTOS CASCADE CONSTRAINTS purge;
--DROP TABLE IF EXISTS TK_CAT_PRIORIDADES CASCADE CONSTRAINTS purge;
--DROP TABLE IF EXISTS TK_CAT_ESTADOS CASCADE CONSTRAINTS purge;

DROP TABLE tk_usuarios CASCADE CONSTRAINTS purge;
DROP TABLE tk_roles CASCADE CONSTRAINTS purge;
DROP TABLE tk_usuarios_roles CASCADE CONSTRAINTS purge;
DROP TABLE tk_comentarios CASCADE CONSTRAINTS purge;
DROP TABLE TK_AREAS CASCADE CONSTRAINTS purge;
DROP TABLE Tk_CATEGORIAS CASCADE CONSTRAINTS purge;
DROP TABLE TK_TICKET_ADJUNTOS CASCADE CONSTRAINTS purge;
DROP TABLE TK_CAT_PRIORIDADES CASCADE CONSTRAINTS purge;
DROP TABLE TK_CAT_ESTADOS CASCADE CONSTRAINTS purge;
DROP TABLE TK_ACTIVOS CASCADE CONSTRAINTS purge;
DROP TABLE TK_ENCUESTAS CASCADE CONSTRAINTS PURGE;
DROP TABLE tk_tickets CASCADE CONSTRAINTS PURGE;

create table tk_usuarios (
    id_usuario integer GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    username VARCHAR2(100) NOT NULL UNIQUE,
    email  VARCHAR2(100) ,
    telefono VARCHAR2(15) ,
    ubicacion VARCHAR2(100) ,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    usuario_creacion VARCHAR2(128) DEFAULT USER NOT NULL,
    fecha_actualizacion TIMESTAMP,
    usuario_actualizacion VARCHAR2(128) ,
    activo CHAR(1) DEFAULT 'S'
); 

ALTER TABLE tk_usuarios ADD CONSTRAINT tk_usuarios_activo_ck CHECK (activo IN ('S', 'N'));

create table tk_roles (
   id_rol INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
   nombre_rol VARCHAR2(100) NOT NULL unique,
   fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
   usuario_creacion VARCHAR2(100) default user NOT NULL,
    fecha_actualizacion TIMESTAMP,
    usuario_actualizacion VARCHAR2(100)
);


CREATE TABLE tk_usuarios_roles (
    id_usuario_rol INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    id_rol INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion VARCHAR2(128) DEFAULT user NOT NULL,
    fecha_actualizacion TIMESTAMP,
    usuario_actualizacion VARCHAR2(128),
    CONSTRAINT tk_usuarios_roles_id_rol_fk FOREIGN KEY (id_rol) REFERENCES tk_roles(id_rol),
    CONSTRAINT tk_usuarios_roles_id_usuario_fk FOREIGN KEY (id_usuario) REFERENCES tk_usuarios(id_usuario)
);

create table tk_comentarios(
    id_comentario integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    id_ticket integer NOT NULL, 
    id_usuario integer NOT NULL,
    comentario varchar2(500) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    usuario_creacion VARCHAR2(128) default user NOT NULL,
    fecha_actualizacion TIMESTAMP,
    usuario_actualizacion VARCHAR2(128)--,
);

CREATE TABLE TK_AREAS (
    ID_AREA integer GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    NOMBRE_AREA VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(300),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    USUARIO_CREACION VARCHAR2(128) DEFAULT USER NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    USUARIO_ACTUALIZACION VARCHAR2(128),
    ACTIVA CHAR(1) DEFAULT 'S'
);

Create table Tk_CATEGORIAS (
    ID_CATEGORIAS integer generated by default on null as identity (start with 1 increment by 1) primary key,
    NOMBRE_CATEGORIAS varchar2 (100) not null,
    DESCRIPCION varchar2 (300) not null,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    USUARIO_CREACION VARCHAR2(128) default user NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP ,
    USUARIO_ACTUALIZACION VARCHAR2(128)
);

CREATE TABLE TK_TICKET_ADJUNTOS (
    ID_ADJUNTO INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    ID_TICKET integer NOT NULL,
    NOMBRE_ARCHIVO VARCHAR2(255),
    EXTENSION VARCHAR2(20),
    MIME_TYPE VARCHAR2(100), 
    TAMANO_BYTES integer,
    ARCHIVO BLOB,  
    FECHA_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO integer NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    USUARIO_CREACION VARCHAR2(128) DEFAULT USER NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    USUARIO_ACTUALIZACION VARCHAR2(128),
    ACTIVA CHAR(1) DEFAULT 'S'
);

create TABLE TK_CAT_PRIORIDADES(
    ID_PRIORIDAD integer GENERATED BY DEFAULT on null as identity (start with 1 increment by 1),
    NOMBRE_PRIORIDAD VARCHAR2(50) NOT NULL,
    NIVEL INTEGER NOT NULL,
    TIEMPO_SLA_HORAS NUMBER NOT NULL, 
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    USUARIO_CREACION VARCHAR2(128) DEFAULT USER NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    USUARIO_ACTUALIZACION VARCHAR2(128),
    CONSTRAINT TK_CAT_PRIORIDADES_ID_PRIORIDAD_PK
    PRIMARY KEY (ID_PRIORIDAD),
    CONSTRAINT TK_CAT_PRIORIDADES_NOMBRE_UK
    UNIQUE (NOMBRE_PRIORIDAD)
);

CREATE TABLE TK_CAT_ESTADOS (
    ID_ESTADO INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    NOMBRE_ESTADO VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPCION_ESTADO VARCHAR2(200),
    CERRADO CHAR(1) DEFAULT 'N' NOT NULL, -- (S/N) Indica si el estado es de cierre de ticket
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    USUARIO_CREACION VARCHAR2(128) DEFAULT USER NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    USUARIO_ACTUALIZACION VARCHAR2(128)
);

CREATE TABLE TK_TIPOS_ACTIVOS (
    ID_TIPO_ACTIVO INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    NOMBRE_TIPO_ACTIVO VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPCION_TIPO_ACTIVO VARCHAR2(200),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    USUARIO_CREACION VARCHAR2(128) DEFAULT USER NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    USUARIO_ACTUALIZACION VARCHAR2(128)
);

CREATE TABLE TK_ACTIVOS
(
  ID_ACTIVO              INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CYCLE CACHE 20 ORDER KEEP NOSCALE) primary key NOT NULL,
  NUMERO_SERIE           VARCHAR2(100)    NOT NULL,
  numero_inventario      VARCHAR2(100),
  DESCRIPCION_ACTIVO     VARCHAR2(200),
  MARCA                  VARCHAR2(128)     NOT NULL,
  MODELO                 VARCHAR2(128)     NOT NULL,
  ID_TIPO_ACTIVO         INTEGER           NOT NULL,
  ID_USUARIO_ASIGNADO    integer           NOT NULL,
  UBICACION              VARCHAR2(128)     NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    USUARIO_CREACION VARCHAR2(128) DEFAULT USER NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    USUARIO_ACTUALIZACION VARCHAR2(128)
);

COMMENT ON TABLE TK_ACTIVOS IS 'tabla correspondiente a activos ';

COMMENT ON COLUMN TK_ACTIVOS.ID_ACTIVO IS 'llave primaria de la tabla de activos ';

CREATE TABLE TK_ENCUESTAS
(
  ID_ENCUESTAS           INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CYCLE CACHE 20 ORDER KEEP NOSCALE) PRIMARY KEY NOT NULL,
  ID_TICKET              INTEGER                NOT NULL,
  CALIFICACION           NUMBER,
  COMENTARIO             VARCHAR2(1000),
  USUARIO_CREACION       VARCHAR2(128)     DEFAULT USER,
  FECHA_CREACION         TIMESTAMP(6)           DEFAULT SYSDATE,
  USUARIO_ACTUALIZACION  VARCHAR2(128),
  FECHA_ACTUALIZACION    TIMESTAMP(6)
);

CREATE TABLE TK_TICKETS (
        id_ticket INTEGER generated by default on null as identity (start with 1 increment by 1) primary key,        
        NOMBRE_TICKET      VARCHAR2(50) NOT NULL,
        descripcion CLOB NOT NULL,
        id_usuario_reporta  integer not null,
        id_tecnico_asignado integer,
        id_categoria   integer not null,
        id_prioridad   integer not null,
        id_estado      integer not null,
        id_area        integer not null,
--        fecha_solicitud  date default sysdate not null,
--        fecha_asignacion date,
--        fecha_inicio     date,
--        fecha_resolucion date,
--        fecha_cierre     date,
        horas_estimadas   number (5,2),
        horas_reales      number (5,2),
        porcentaje_avance number(3,2) default 0,
        descripcion_solucion clob,
        constraint tk_tickets_id_usuario_reporta_fk
               foreign key (id_usuario_reporta)
               references tk_usuarios(id_usuario),        
        constraint tk_tickets_id_tecnico_asignado_fk
               foreign key (id_tecnico_asignado)
               references tk_usuarios(id_usuario),
        constraint tk_tickets_id_categoria_fk
               foreign key (id_categoria)
               references tk_categorias (id_categoria),
        constraint tk_tickets_id_estado_fk
               foreign key (id_estado)
                references tk_estados (id_estado),
        constraint tk_tickets_id_area_fk
               foreign key (id_area)
                references tk_areas (id_area),
        constraint tk_tickets_id_prioridad_fk
               foreign key (id_prioridad)
                references tk_prioridades (id_prioridad),
        constraint tk_tickets_porcentaje_avance_ck
               check (porcentaje_avance between 0 and 100)
        constraint tk_tickets_horas_estimadas_ck
               check (horas_estimadas >= 0),
        constraint tk_tickets_horas_reales_ck
               check (horas_reales >= 0),
  USUARIO_CREACION       VARCHAR2(128)     DEFAULT USER,
  FECHA_CREACION         TIMESTAMP(6)      DEFAULT SYSDATE,
  USUARIO_ACTUALIZACION  VARCHAR2(128),
  FECHA_ACTUALIZACION    TIMESTAMP(6)
);

create table tk_activos_tickets (
    id_activo_ticket integer generated by default on null as identity (start with 1 increment by 1) primary key,
    id_activo integer not null,
    id_ticket integer not null,
    constraint tk_activos_tickets_id_activo_fk
           foreign key (id_activo)
           references tk_activos(id_activo),
    constraint tk_activos_tickets_id_ticket_fk
           foreign key (id_ticket)
           references tk_tickets(id_ticket)
);

-- create table tk_tickets_historial (
--    id_t_historial INT GENERATED BY DEFAULT AS IDENTITY
--         (START WITH 1 INCREMENT BY 1)
--         PRIMARY KEY,

--     id_ticket INT NOT NULL,
--     id_usuario INT NOT NULL,
     

--     fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
--     usuario_creacion VARCHAR2(128) DEFAULT USER NOT NULL,

--     fecha_actualizacion TIMESTAMP,
--     usuario_actualizacion VARCHAR2(128)

-- );


--ALTER TABLE tk_comentarios ADD CONSTRAINT tk_comentarios_id_usuario_fk FOREIGN KEY (id_usuario) REFERENCES tk_usuarios(id_usuario);
--ALTER TABLE tk_comentarios ADD CONSTRAINT tk_comentarios_id_ticket_fk FOREIGN KEY (id_ticket) REFERENCES tk_tickets(id_ticket);
--ALTER TABLE TK_COMENTARIOS ADD CONSTRAINT tk_comentarios_id_ticket_fk FOREIGN KEY (id_ticket) REFERENCES tk_tickets(id_ticket);

