-- CREA TABLAS --

create table tk_usuarios (
    id_usuario integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    username VARCHAR2(100) NOT NULL UNIQUE,
    email  VARCHAR2(100) ,
    telefono VARCHAR2(15) ,
    ubicacion VARCHAR2(100) ,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    usuario_creacion VARCHAR2(128) DEFAULT USER NOT NULL,
    fecha_actualizacion TIMESTAMP,
    usuario_actualizacion VARCHAR2(128) 
); 

create table tk_roles (
   id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
   nombre_rol VARCHAR2(100) NOT NULL unique,
   fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
   usuario_creacion VARCHAR2(100) default user NOT NULL,
    fecha_actualizacion TIMESTAMP,
    usuario_actualizacion VARCHAR2(100)
);


CREATE TABLE tk_usuarios_roles (
    id_usuario_rol INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    id_rol INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion VARCHAR2(128) DEFAULT user NOT NULL,
    fecha_actualizacion TIMESTAMP,
    usuario_actualizacion VARCHAR2(128),
    CONSTRAINT tk_usuarios_roles_id_rol_fk FOREIGN KEY (id_rol) REFERENCES tk_roles(id_rol),
    CONSTRAINT tk_usuarios_roles_id_usuario_fk FOREIGN KEY (id_usuario) REFERENCES tk_usuarios(id_usuario)
);

