-- Spec CRUD para TICKETS.TK_BASE_CONOCIMIENTOS_CRUD_PKG
CONNECT TICKETS/Tickets123@192.168.80.178:1521/FREEpdb1
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE OR REPLACE PACKAGE TICKETS.TK_BASE_CONOCIMIENTOS_CRUD_PKG AS

    PROCEDURE TK_BASE_CONOCIMIENTOS_CREAR_P(
        p_id_base_conocimiento           IN  TICKETS.TK_BASE_CONOCIMIENTOS.ID_BASE_CONOCIMIENTO%TYPE,
        p_titulo                         IN  TICKETS.TK_BASE_CONOCIMIENTOS.TITULO%TYPE,
        p_descripcion                    IN  TICKETS.TK_BASE_CONOCIMIENTOS.DESCRIPCION%TYPE,
        p_palabras_clave                 IN  TICKETS.TK_BASE_CONOCIMIENTOS.PALABRAS_CLAVE%TYPE,
        p_publicado                      IN  TICKETS.TK_BASE_CONOCIMIENTOS.PUBLICADO%TYPE,
        p_id_usuario_autor               IN  TICKETS.TK_BASE_CONOCIMIENTOS.ID_USUARIO_AUTOR%TYPE,
        p_fecha_creacion                 IN  TICKETS.TK_BASE_CONOCIMIENTOS.FECHA_CREACION%TYPE,
        p_usuario_creacion               IN  TICKETS.TK_BASE_CONOCIMIENTOS.USUARIO_CREACION%TYPE,
        p_fecha_actualizacion            IN  TICKETS.TK_BASE_CONOCIMIENTOS.FECHA_ACTUALIZACION%TYPE,
        p_usuario_actualizacion          IN  TICKETS.TK_BASE_CONOCIMIENTOS.USUARIO_ACTUALIZACION%TYPE,
        po_ID_BASE_CONOCIMIENTO_generado  OUT TICKETS.TK_BASE_CONOCIMIENTOS.ID_BASE_CONOCIMIENTO%TYPE,
        pv_resultado                 OUT VARCHAR2
    );

    PROCEDURE TK_BASE_CONOCIMIENTOS_ACTUALIZAR_P(
        p_id_base_conocimiento           IN  TICKETS.TK_BASE_CONOCIMIENTOS.ID_BASE_CONOCIMIENTO%TYPE,
        p_titulo                         IN  TICKETS.TK_BASE_CONOCIMIENTOS.TITULO%TYPE,
        p_descripcion                    IN  TICKETS.TK_BASE_CONOCIMIENTOS.DESCRIPCION%TYPE,
        p_palabras_clave                 IN  TICKETS.TK_BASE_CONOCIMIENTOS.PALABRAS_CLAVE%TYPE,
        p_publicado                      IN  TICKETS.TK_BASE_CONOCIMIENTOS.PUBLICADO%TYPE,
        p_id_usuario_autor               IN  TICKETS.TK_BASE_CONOCIMIENTOS.ID_USUARIO_AUTOR%TYPE,
        p_fecha_creacion                 IN  TICKETS.TK_BASE_CONOCIMIENTOS.FECHA_CREACION%TYPE,
        p_usuario_creacion               IN  TICKETS.TK_BASE_CONOCIMIENTOS.USUARIO_CREACION%TYPE,
        p_fecha_actualizacion            IN  TICKETS.TK_BASE_CONOCIMIENTOS.FECHA_ACTUALIZACION%TYPE,
        p_usuario_actualizacion          IN  TICKETS.TK_BASE_CONOCIMIENTOS.USUARIO_ACTUALIZACION%TYPE,
        pv_resultado                 OUT VARCHAR2
    );

    PROCEDURE TK_BASE_CONOCIMIENTOS_ELIMINAR_P(
        p_ID_BASE_CONOCIMIENTO           IN  TICKETS.TK_BASE_CONOCIMIENTOS.ID_BASE_CONOCIMIENTO%TYPE,
        pv_resultado                 OUT VARCHAR2
    );

    FUNCTION TK_BASE_CONOCIMIENTOS_CONSULTAR_F(
        p_ID_BASE_CONOCIMIENTO           IN  TICKETS.TK_BASE_CONOCIMIENTOS.ID_BASE_CONOCIMIENTO%TYPE DEFAULT NULL
    ) RETURN SYS_REFCURSOR;

END TK_BASE_CONOCIMIENTOS_CRUD_PKG;
/

