-- Spec CRUD para TICKETS.TK_USUARIOS_ROLES_CRUD_PKG
CONNECT TICKETS/Tickets123
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE OR REPLACE PACKAGE TICKETS.TK_USUARIOS_ROLES_CRUD_PKG AS

    PROCEDURE TK_USUARIOS_ROLES_CREAR_P(
        p_id_usuario_rol                 IN  TICKETS.TK_USUARIOS_ROLES.ID_USUARIO_ROL%TYPE,
        p_id_rol                         IN  TICKETS.TK_USUARIOS_ROLES.ID_ROL%TYPE,
        p_id_usuario                     IN  TICKETS.TK_USUARIOS_ROLES.ID_USUARIO%TYPE,
        p_fecha_creacion                 IN  TICKETS.TK_USUARIOS_ROLES.FECHA_CREACION%TYPE,
        p_usuario_creacion               IN  TICKETS.TK_USUARIOS_ROLES.USUARIO_CREACION%TYPE,
        p_fecha_actualizacion            IN  TICKETS.TK_USUARIOS_ROLES.FECHA_ACTUALIZACION%TYPE,
        p_usuario_actualizacion          IN  TICKETS.TK_USUARIOS_ROLES.USUARIO_ACTUALIZACION%TYPE,
        po_ID_USUARIO_ROL_generado     OUT TICKETS.TK_USUARIOS_ROLES.ID_USUARIO_ROL%TYPE,
        pv_resultado                 OUT VARCHAR2
    );

    PROCEDURE TK_USUARIOS_ROLES_ACTUALIZAR_P(
        p_id_usuario_rol                 IN  TICKETS.TK_USUARIOS_ROLES.ID_USUARIO_ROL%TYPE,
        p_id_rol                         IN  TICKETS.TK_USUARIOS_ROLES.ID_ROL%TYPE,
        p_id_usuario                     IN  TICKETS.TK_USUARIOS_ROLES.ID_USUARIO%TYPE,
        p_fecha_creacion                 IN  TICKETS.TK_USUARIOS_ROLES.FECHA_CREACION%TYPE,
        p_usuario_creacion               IN  TICKETS.TK_USUARIOS_ROLES.USUARIO_CREACION%TYPE,
        p_fecha_actualizacion            IN  TICKETS.TK_USUARIOS_ROLES.FECHA_ACTUALIZACION%TYPE,
        p_usuario_actualizacion          IN  TICKETS.TK_USUARIOS_ROLES.USUARIO_ACTUALIZACION%TYPE,
        pv_resultado                 OUT VARCHAR2
    );

    PROCEDURE TK_USUARIOS_ROLES_ELIMINAR_P(
        p_ID_USUARIO_ROL                 IN  TICKETS.TK_USUARIOS_ROLES.ID_USUARIO_ROL%TYPE,
        pv_resultado                 OUT VARCHAR2
    );

    FUNCTION TK_USUARIOS_ROLES_CONSULTAR_F(
        p_ID_USUARIO_ROL                 IN  TICKETS.TK_USUARIOS_ROLES.ID_USUARIO_ROL%TYPE DEFAULT NULL
    ) RETURN SYS_REFCURSOR;

END TK_USUARIOS_ROLES_CRUD_PKG;
/

