-- Spec CRUD para TICKETS.TK_ACTIVOS_TICKETS_CRUD_PKG
CONNECT TICKETS/Tickets123
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE OR REPLACE PACKAGE TICKETS.TK_ACTIVOS_TICKETS_CRUD_PKG AS

    PROCEDURE TK_ACTIVOS_TICKETS_CREAR_P(
        p_id_activo_ticket               IN  TICKETS.TK_ACTIVOS_TICKETS.ID_ACTIVO_TICKET%TYPE,
        p_id_activo                      IN  TICKETS.TK_ACTIVOS_TICKETS.ID_ACTIVO%TYPE,
        p_id_ticket                      IN  TICKETS.TK_ACTIVOS_TICKETS.ID_TICKET%TYPE,
        p_fecha_creacion                 IN  TICKETS.TK_ACTIVOS_TICKETS.FECHA_CREACION%TYPE,
        p_usuario_creacion               IN  TICKETS.TK_ACTIVOS_TICKETS.USUARIO_CREACION%TYPE,
        p_fecha_actualizacion            IN  TICKETS.TK_ACTIVOS_TICKETS.FECHA_ACTUALIZACION%TYPE,
        p_usuario_actualizacion          IN  TICKETS.TK_ACTIVOS_TICKETS.USUARIO_ACTUALIZACION%TYPE,
        po_ID_ACTIVO_TICKET_generado   OUT TICKETS.TK_ACTIVOS_TICKETS.ID_ACTIVO_TICKET%TYPE,
        pv_resultado                 OUT VARCHAR2
    );

    PROCEDURE TK_ACTIVOS_TICKETS_ACTUALIZAR_P(
        p_id_activo_ticket               IN  TICKETS.TK_ACTIVOS_TICKETS.ID_ACTIVO_TICKET%TYPE,
        p_id_activo                      IN  TICKETS.TK_ACTIVOS_TICKETS.ID_ACTIVO%TYPE,
        p_id_ticket                      IN  TICKETS.TK_ACTIVOS_TICKETS.ID_TICKET%TYPE,
        p_fecha_creacion                 IN  TICKETS.TK_ACTIVOS_TICKETS.FECHA_CREACION%TYPE,
        p_usuario_creacion               IN  TICKETS.TK_ACTIVOS_TICKETS.USUARIO_CREACION%TYPE,
        p_fecha_actualizacion            IN  TICKETS.TK_ACTIVOS_TICKETS.FECHA_ACTUALIZACION%TYPE,
        p_usuario_actualizacion          IN  TICKETS.TK_ACTIVOS_TICKETS.USUARIO_ACTUALIZACION%TYPE,
        pv_resultado                 OUT VARCHAR2
    );

    PROCEDURE TK_ACTIVOS_TICKETS_ELIMINAR_P(
        p_ID_ACTIVO_TICKET               IN  TICKETS.TK_ACTIVOS_TICKETS.ID_ACTIVO_TICKET%TYPE,
        pv_resultado                 OUT VARCHAR2
    );

    FUNCTION TK_ACTIVOS_TICKETS_CONSULTAR_F(
        p_ID_ACTIVO_TICKET               IN  TICKETS.TK_ACTIVOS_TICKETS.ID_ACTIVO_TICKET%TYPE DEFAULT NULL
    ) RETURN SYS_REFCURSOR;

END TK_ACTIVOS_TICKETS_CRUD_PKG;
/
