-- Datos semilla para TK_CAT_PRIORIDADES
SET DEFINE ON
CONNECT &DB_USER/&DB_PASSWORD@&DB_CONNECT
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

MERGE INTO TICKETS.TK_CAT_PRIORIDADES t
USING (
    SELECT 'Crítica' AS nombre_prioridad, 1 AS nivel, 4 AS tiempo_sla_horas, 'S' AS activa FROM DUAL
    UNION ALL SELECT 'Alta', 2, 8, 'S' FROM DUAL
    UNION ALL SELECT 'Media', 3, 24, 'S' FROM DUAL
    UNION ALL SELECT 'Baja', 4, 72, 'S' FROM DUAL
) s
ON (t.NOMBRE_PRIORIDAD = s.NOMBRE_PRIORIDAD)
WHEN MATCHED THEN UPDATE SET
    t.NIVEL = s.NIVEL,
    t.TIEMPO_SLA_HORAS = s.TIEMPO_SLA_HORAS,
    t.ACTIVA = s.ACTIVA
WHEN NOT MATCHED THEN INSERT (
    NOMBRE_PRIORIDAD, NIVEL, TIEMPO_SLA_HORAS, ACTIVA
)
VALUES (
    s.NOMBRE_PRIORIDAD, s.NIVEL, s.TIEMPO_SLA_HORAS, s.ACTIVA
);

COMMIT;
