-- Pruebas unitarias para TICKETS.TK_TICKET_ADJUNTOS_CRUD_PKG
CONNECT TICKETS/Tickets123@&DB_CONNECT
SET SERVEROUTPUT ON
SET DEFINE ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
DECLARE
 v_id NUMBER; v_gen NUMBER; v_ticket NUMBER; v_usr NUMBER; v_cat NUMBER; v_pri NUMBER; v_est NUMBER; v_area NUMBER; v_cur SYS_REFCURSOR; v_res VARCHAR2(4000); v_blob BLOB; v_fc TIMESTAMP; v_uc VARCHAR2(128);
 PROCEDURE ok(p BOOLEAN,m VARCHAR2) IS BEGIN IF NOT p THEN RAISE_APPLICATION_ERROR(-20999,'FALLO: '||m); END IF; DBMS_OUTPUT.PUT_LINE('OK: '||m); END;
BEGIN
 SELECT ID_USUARIO INTO v_usr FROM TICKETS.TK_USUARIOS WHERE USERNAME='usuario.tickets' AND ACTIVO='S'; SELECT ID_CATEGORIA INTO v_cat FROM TICKETS.TK_CATEGORIAS WHERE NOMBRE_CATEGORIA='Incidentes' AND ACTIVA='S'; SELECT ID_PRIORIDAD INTO v_pri FROM TICKETS.TK_CAT_PRIORIDADES WHERE NOMBRE_PRIORIDAD='Media' AND ACTIVA='S'; SELECT ID_ESTADO INTO v_est FROM TICKETS.TK_CAT_ESTADOS WHERE NOMBRE_ESTADO='Nuevo' AND ACTIVO='S'; SELECT ID_AREA INTO v_area FROM TICKETS.TK_AREAS WHERE NOMBRE_AREA='Mesa de Ayuda' AND ACTIVA='S';
 TICKETS.TK_TICKETS_NEGOCIO_PKG.CREAR_TICKET('TEST ADJUNTO '||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3'),TO_CLOB('Ticket temporal'),v_usr,v_cat,v_pri,v_area,1,v_ticket,v_gen,v_res,v_res); ok(v_gen=1 AND v_ticket IS NOT NULL,'crear ticket temporal');
 DBMS_LOB.CREATETEMPORARY(v_blob,TRUE); DBMS_LOB.WRITEAPPEND(v_blob,5,UTL_RAW.CAST_TO_RAW('hola!'));
 TICKETS.TK_TICKET_ADJUNTOS_CRUD_PKG.TK_TICKET_ADJUNTOS_CREAR_P(NULL,v_ticket,'test.txt','txt','text/plain',5,v_blob,NULL,v_usr,SYSTIMESTAMP,SYSTIMESTAMP,USER,NULL,NULL,'S',v_gen,v_res); ok(v_res='OK: REGISTRO CREADO','crear adjunto'); v_id:=v_gen;
 v_cur:=TICKETS.TK_TICKET_ADJUNTOS_CRUD_PKG.TK_TICKET_ADJUNTOS_CONSULTAR_F(v_id); CLOSE v_cur; SELECT FECHA_CREACION,USUARIO_CREACION INTO v_fc,v_uc FROM TICKETS.TK_TICKET_ADJUNTOS WHERE ID_ADJUNTO=v_id; ok(v_id IS NOT NULL,'consultar adjunto');
 TICKETS.TK_TICKET_ADJUNTOS_CRUD_PKG.TK_TICKET_ADJUNTOS_ACTUALIZAR_P(v_id,v_ticket,'test2.txt','txt','text/plain',5,v_blob,NULL,v_usr,SYSTIMESTAMP,v_fc,v_uc,NULL,NULL,'N',v_res); ok(v_res='OK: REGISTRO ACTUALIZADO','actualizar adjunto');
 TICKETS.TK_TICKET_ADJUNTOS_CRUD_PKG.TK_TICKET_ADJUNTOS_ELIMINAR_P(v_id,v_res); ok(v_res='OK: REGISTRO ELIMINADO','eliminar adjunto'); DBMS_LOB.FREETEMPORARY(v_blob); DELETE FROM TICKETS.TK_TICKETS_HISTORIAL WHERE ID_TICKET=v_ticket; DELETE FROM TICKETS.TK_TICKETS WHERE ID_TICKET=v_ticket; COMMIT; DBMS_OUTPUT.PUT_LINE('=== TODAS LAS PRUEBAS TK_TICKET_ADJUNTOS PASARON ===');
EXCEPTION WHEN OTHERS THEN IF v_cur%ISOPEN THEN CLOSE v_cur; END IF; IF DBMS_LOB.ISTEMPORARY(v_blob)=1 THEN DBMS_LOB.FREETEMPORARY(v_blob); END IF; IF v_ticket IS NOT NULL THEN DELETE FROM TICKETS.TK_TICKET_ADJUNTOS WHERE ID_TICKET=v_ticket; DELETE FROM TICKETS.TK_TICKETS_HISTORIAL WHERE ID_TICKET=v_ticket; DELETE FROM TICKETS.TK_TICKETS WHERE ID_TICKET=v_ticket; COMMIT; END IF; RAISE;
END;
/
