-- Pruebas unitarias para TICKETS.TK_TIPOS_ACTIVOS_CRUD_PKG
CONNECT &DB_USER/&DB_PASSWORD@&DB_CONNECT
SET SERVEROUTPUT ON
SET DEFINE ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
DECLARE
    v_id TICKETS.TK_TIPOS_ACTIVOS.ID_TIPO_ACTIVO%TYPE;
    v_gen TICKETS.TK_TIPOS_ACTIVOS.ID_TIPO_ACTIVO%TYPE;
    v_fc TICKETS.TK_TIPOS_ACTIVOS.FECHA_CREACION%TYPE;
    v_uc TICKETS.TK_TIPOS_ACTIVOS.USUARIO_CREACION%TYPE;
    v_cur SYS_REFCURSOR; v_res VARCHAR2(4000);
    v_name VARCHAR2(100) := 'TEST TIPO ' || TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
    PROCEDURE ok(p BOOLEAN, m VARCHAR2) IS BEGIN IF NOT p THEN RAISE_APPLICATION_ERROR(-20999,'FALLO: '||m); END IF; DBMS_OUTPUT.PUT_LINE('OK: '||m); END;
BEGIN
    TICKETS.TK_TIPOS_ACTIVOS_CRUD_PKG.TK_TIPOS_ACTIVOS_CREAR_P(NULL,v_name,'Tipo temporal',NULL,NULL,NULL,NULL,'S',v_gen,v_res);
    ok(v_res='OK: REGISTRO CREADO' AND v_gen IS NOT NULL,'crear tipo de activo'); v_id:=v_gen;
    v_cur:=TICKETS.TK_TIPOS_ACTIVOS_CRUD_PKG.TK_TIPOS_ACTIVOS_CONSULTAR_F(v_id); FETCH v_cur INTO v_gen,v_name,v_res,v_fc,v_uc,v_fc,v_uc,v_res; CLOSE v_cur;
    SELECT FECHA_CREACION, USUARIO_CREACION INTO v_fc, v_uc FROM TICKETS.TK_TIPOS_ACTIVOS WHERE ID_TIPO_ACTIVO=v_id;
    ok(v_gen=v_id,'consultar tipo de activo');
    TICKETS.TK_TIPOS_ACTIVOS_CRUD_PKG.TK_TIPOS_ACTIVOS_ACTUALIZAR_P(v_id,v_name||' ACTUALIZADO','Descripcion actualizada',v_fc,v_uc,NULL,NULL,'N',v_res);
    ok(v_res='OK: REGISTRO ACTUALIZADO','actualizar tipo de activo');
    TICKETS.TK_TIPOS_ACTIVOS_CRUD_PKG.TK_TIPOS_ACTIVOS_CREAR_P(NULL,v_name||' ACTUALIZADO','Duplicado',NULL,NULL,NULL,NULL,'S',v_gen,v_res);
    ok(v_res LIKE 'ERROR:%' AND v_gen IS NULL,'rechazar nombre duplicado');
    TICKETS.TK_TIPOS_ACTIVOS_CRUD_PKG.TK_TIPOS_ACTIVOS_ACTUALIZAR_P(v_id,v_name||' ACTUALIZADO','No debe actualizarse',v_fc,v_uc,NULL,NULL,'X',v_res);
    ok(v_res LIKE 'ERROR:%','rechazar ACTIVO invalido');
    TICKETS.TK_TIPOS_ACTIVOS_CRUD_PKG.TK_TIPOS_ACTIVOS_ELIMINAR_P(v_id,v_res); ok(v_res='OK: REGISTRO ELIMINADO','eliminar tipo de activo');
    DBMS_OUTPUT.PUT_LINE('=== TODAS LAS PRUEBAS TK_TIPOS_ACTIVOS PASARON ===');
EXCEPTION WHEN OTHERS THEN IF v_cur%ISOPEN THEN CLOSE v_cur; END IF; IF v_id IS NOT NULL THEN DELETE FROM TICKETS.TK_TIPOS_ACTIVOS WHERE ID_TIPO_ACTIVO=v_id; COMMIT; END IF; RAISE;
END;
/
