-- Pruebas unitarias para TICKETS.TK_ACTIVOS_CRUD_PKG
CONNECT &DB_USER/&DB_PASSWORD@&DB_CONNECT
SET SERVEROUTPUT ON
SET DEFINE ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
DECLARE
    v_id TICKETS.TK_ACTIVOS.ID_ACTIVO%TYPE; v_gen TICKETS.TK_ACTIVOS.ID_ACTIVO%TYPE;
    v_tipo TICKETS.TK_TIPOS_ACTIVOS.ID_TIPO_ACTIVO%TYPE; v_usr TICKETS.TK_USUARIOS.ID_USUARIO%TYPE;
    v_fc TICKETS.TK_ACTIVOS.FECHA_CREACION%TYPE; v_uc TICKETS.TK_ACTIVOS.USUARIO_CREACION%TYPE;
    v_cur SYS_REFCURSOR; v_res VARCHAR2(4000); v_serie VARCHAR2(100):='TEST-SERIE-'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
    PROCEDURE ok(p BOOLEAN,m VARCHAR2) IS BEGIN IF NOT p THEN RAISE_APPLICATION_ERROR(-20999,'FALLO: '||m); END IF; DBMS_OUTPUT.PUT_LINE('OK: '||m); END;
BEGIN
    SELECT MIN(ID_TIPO_ACTIVO) INTO v_tipo FROM TICKETS.TK_TIPOS_ACTIVOS;
    SELECT MIN(ID_USUARIO) INTO v_usr FROM TICKETS.TK_USUARIOS WHERE ACTIVO='S';
    ok(v_tipo IS NOT NULL AND v_usr IS NOT NULL,'encontrar referencias de activo');
    TICKETS.TK_ACTIVOS_CRUD_PKG.TK_ACTIVOS_CREAR_P(NULL,v_serie,'TEST-INV-'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3'),'Activo temporal','Marca','Modelo',v_tipo,v_usr,'Laboratorio',NULL,NULL,NULL,NULL,'S',v_gen,v_res);
    ok(v_res='OK: REGISTRO CREADO' AND v_gen IS NOT NULL,'crear activo valido'); v_id:=v_gen;
    v_cur:=TICKETS.TK_ACTIVOS_CRUD_PKG.TK_ACTIVOS_CONSULTAR_F(v_id); FETCH v_cur INTO v_gen,v_serie,v_res,v_res,v_res,v_res,v_tipo,v_usr,v_res,v_fc,v_uc,v_fc,v_uc,v_res; CLOSE v_cur;
    SELECT FECHA_CREACION, USUARIO_CREACION INTO v_fc, v_uc FROM TICKETS.TK_ACTIVOS WHERE ID_ACTIVO=v_id;
    ok(v_gen=v_id,'consultar activo');
    TICKETS.TK_ACTIVOS_CRUD_PKG.TK_ACTIVOS_ACTUALIZAR_P(v_id,v_serie,'TEST-INV-ACT','Activo actualizado','Marca2','Modelo2',v_tipo,v_usr,'Oficina',v_fc,v_uc,NULL,NULL,'N',v_res);
    ok(v_res='OK: REGISTRO ACTUALIZADO','actualizar activo');
    TICKETS.TK_ACTIVOS_CRUD_PKG.TK_ACTIVOS_CREAR_P(NULL,NULL,NULL,'No debe insertarse',NULL,NULL,v_tipo,NULL,NULL,NULL,NULL,NULL,NULL,'S',v_gen,v_res);
    ok(v_res LIKE 'ERROR:%' AND v_gen IS NULL,'rechazar numero de serie nulo');
    TICKETS.TK_ACTIVOS_CRUD_PKG.TK_ACTIVOS_ELIMINAR_P(v_id,v_res); ok(v_res='OK: REGISTRO ELIMINADO','eliminar activo');
    DBMS_OUTPUT.PUT_LINE('=== TODAS LAS PRUEBAS TK_ACTIVOS PASARON ===');
EXCEPTION WHEN OTHERS THEN IF v_cur%ISOPEN THEN CLOSE v_cur; END IF; IF v_id IS NOT NULL THEN DELETE FROM TICKETS.TK_ACTIVOS WHERE ID_ACTIVO=v_id; COMMIT; END IF; RAISE;
END;
/
