-- Pruebas unitarias para TICKETS.TK_ACTIVOS_TICKETS_CRUD_PKG
CONNECT TICKETS/Tickets123@&DB_CONNECT
SET SERVEROUTPUT ON
SET DEFINE ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
DECLARE
    v_id TICKETS.TK_ACTIVOS_TICKETS.ID_ACTIVO_TICKET%TYPE; v_gen TICKETS.TK_ACTIVOS_TICKETS.ID_ACTIVO_TICKET%TYPE;
    v_act TICKETS.TK_ACTIVOS.ID_ACTIVO%TYPE; v_tic TICKETS.TK_TICKETS.ID_TICKET%TYPE;
    v_tmp_asset TICKETS.TK_ACTIVOS.ID_ACTIVO%TYPE; v_tmp_ticket TICKETS.TK_TICKETS.ID_TICKET%TYPE;
    v_usr NUMBER; v_tipo NUMBER; v_cat NUMBER; v_pri NUMBER; v_est NUMBER; v_area NUMBER;
    v_fc TICKETS.TK_ACTIVOS_TICKETS.FECHA_CREACION%TYPE; v_uc TICKETS.TK_ACTIVOS_TICKETS.USUARIO_CREACION%TYPE;
    v_cur SYS_REFCURSOR; v_res VARCHAR2(4000);
    PROCEDURE ok(p BOOLEAN,m VARCHAR2) IS BEGIN IF NOT p THEN RAISE_APPLICATION_ERROR(-20999,'FALLO: '||m); END IF; DBMS_OUTPUT.PUT_LINE('OK: '||m); END;
BEGIN
    SELECT MIN(ID_USUARIO) INTO v_usr FROM TICKETS.TK_USUARIOS WHERE ACTIVO='S';
    SELECT MIN(ID_TIPO_ACTIVO) INTO v_tipo FROM TICKETS.TK_TIPOS_ACTIVOS WHERE ACTIVO='S';
    SELECT MIN(ID_CATEGORIA) INTO v_cat FROM TICKETS.TK_CATEGORIAS WHERE ACTIVA='S';
    SELECT MIN(ID_PRIORIDAD) INTO v_pri FROM TICKETS.TK_CAT_PRIORIDADES WHERE ACTIVA='S';
    SELECT MIN(ID_ESTADO) INTO v_est FROM TICKETS.TK_CAT_ESTADOS WHERE ACTIVO='S';
    SELECT MIN(ID_AREA) INTO v_area FROM TICKETS.TK_AREAS WHERE ACTIVA='S';
    TICKETS.TK_TICKETS_NEGOCIO_PKG.CREAR_TICKET(
        'TEST RELACION '||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3'),
        TO_CLOB('Ticket temporal para relacion'),v_usr,v_cat,v_pri,v_area,1,
        v_tmp_ticket,v_gen,v_res,v_res);
    TICKETS.TK_ACTIVOS_CRUD_PKG.TK_ACTIVOS_CREAR_P(
        NULL,'TEST-ACT-'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3'),
        'TEST-INV-'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3'),
        'Activo temporal','Marca','Modelo',v_tipo,v_usr,'Laboratorio',
        NULL,NULL,NULL,NULL,'S',v_gen,v_res);
    v_tmp_asset:=v_gen; v_act:=v_tmp_asset; v_tic:=v_tmp_ticket;
    ok(v_act IS NOT NULL AND v_tic IS NOT NULL,'encontrar activo y ticket');
    TICKETS.TK_ACTIVOS_TICKETS_CRUD_PKG.TK_ACTIVOS_TICKETS_CREAR_P(NULL,v_act,v_tic,NULL,NULL,NULL,NULL,v_gen,v_res);
    ok(v_res='OK: REGISTRO CREADO' AND v_gen IS NOT NULL,'crear relacion activo-ticket'); v_id:=v_gen;
    v_cur:=TICKETS.TK_ACTIVOS_TICKETS_CRUD_PKG.TK_ACTIVOS_TICKETS_CONSULTAR_F(v_id); FETCH v_cur INTO v_gen,v_act,v_tic,v_fc,v_uc,v_fc,v_uc; CLOSE v_cur;
    SELECT FECHA_CREACION, USUARIO_CREACION INTO v_fc, v_uc FROM TICKETS.TK_ACTIVOS_TICKETS WHERE ID_ACTIVO_TICKET=v_id;
    ok(v_gen=v_id,'consultar relacion activo-ticket');
    TICKETS.TK_ACTIVOS_TICKETS_CRUD_PKG.TK_ACTIVOS_TICKETS_ACTUALIZAR_P(v_id,v_act,v_tic,v_fc,v_uc,NULL,NULL,v_res);
    ok(v_res='OK: REGISTRO ACTUALIZADO','actualizar relacion activo-ticket');
    TICKETS.TK_ACTIVOS_TICKETS_CRUD_PKG.TK_ACTIVOS_TICKETS_CREAR_P(NULL,v_act,v_tic,NULL,NULL,NULL,NULL,v_gen,v_res);
    ok(v_res LIKE 'ERROR:%' AND v_gen IS NULL,'rechazar relacion duplicada');
    TICKETS.TK_ACTIVOS_TICKETS_CRUD_PKG.TK_ACTIVOS_TICKETS_ELIMINAR_P(v_id,v_res); ok(v_res='OK: REGISTRO ELIMINADO','eliminar relacion activo-ticket');
    DELETE FROM TICKETS.TK_ACTIVOS WHERE ID_ACTIVO=v_tmp_asset;
    DELETE FROM TICKETS.TK_TICKETS_HISTORIAL WHERE ID_TICKET=v_tmp_ticket;
    DELETE FROM TICKETS.TK_TICKETS WHERE ID_TICKET=v_tmp_ticket;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('=== TODAS LAS PRUEBAS TK_ACTIVOS_TICKETS PASARON ===');
EXCEPTION WHEN OTHERS THEN IF v_cur%ISOPEN THEN CLOSE v_cur; END IF; IF v_id IS NOT NULL THEN DELETE FROM TICKETS.TK_ACTIVOS_TICKETS WHERE ID_ACTIVO_TICKET=v_id; END IF; IF v_tmp_asset IS NOT NULL THEN DELETE FROM TICKETS.TK_ACTIVOS WHERE ID_ACTIVO=v_tmp_asset; END IF; IF v_tmp_ticket IS NOT NULL THEN DELETE FROM TICKETS.TK_TICKETS_HISTORIAL WHERE ID_TICKET=v_tmp_ticket; DELETE FROM TICKETS.TK_TICKETS WHERE ID_TICKET=v_tmp_ticket; END IF; COMMIT; RAISE;
END;
/
