-- Maestro de pruebas integrales.

SET ECHO OFF
SET FEEDBACK OFF
SET SERVEROUTPUT ON
SET DEFINE ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
ACCEPT DB_USER CHAR DEFAULT TICKETS PROMPT 'Usuario [TICKETS]: '
ACCEPT DB_PASSWORD CHAR DEFAULT Tickets123 HIDE PROMPT 'Password [Tickets123]: '
ACCEPT DB_CONNECT CHAR DEFAULT '//192.168.0.17:1521/freepdb1' PROMPT 'EZ Connect [//192.168.0.17:1521/freepdb1]: '

PROMPT [01/01] flujo completo de ticket ...
SET TERMOUT OFF
@@001-test-flujo-ticket-completo.sql
SET TERMOUT ON
PROMPT [OK] flujo completo de ticket
PROMPT === TODAS LAS PRUEBAS INTEGRALES PASARON ===

EXIT
