-- Correr con un DBA
-- Requiere una conexión activa como SYS AS SYSDBA.

-- Usuario de desarrollo para el proyecto de tickets
CREATE USER TICKETS IDENTIFIED BY &TICKETS_PASSWORD
    DEFAULT TABLESPACE TBS_TICKETS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON TBS_TICKETS;

-- Acceso a la base de datos y privilegios de desarrollo
GRANT CREATE SESSION TO TICKETS;
GRANT CREATE TABLE TO TICKETS;
GRANT CREATE SEQUENCE TO TICKETS;
GRANT CREATE VIEW TO TICKETS;
GRANT CREATE MATERIALIZED VIEW TO TICKETS;
GRANT CREATE PROCEDURE TO TICKETS;
GRANT CREATE TRIGGER TO TICKETS;
GRANT CREATE TYPE TO TICKETS;
GRANT CREATE SYNONYM TO TICKETS;
GRANT CREATE JOB TO TICKETS;

-- Permite depurar las sesiones propias del usuario
GRANT DEBUG CONNECT SESSION TO TICKETS;
